name: Reusable workflow example

#SI POSSONO ANCHE METTERE DEGLI INPUT CHE VENGONO PASSATI dal Caller!!! Anche segreti possono essere passati dal caller!!!

on:
  workflow_call:
  # inputs:
  #   username:
  #     required: true
  #     type: string
#    secrets:
#      FIREBASE_CREDENTIALS:
#        required: true
jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
#    env:
#      firebase_credentials: ${{ secrets.FIREBASE_CREDENTIALS }}
    steps:
      #- uses: ./.github/workflows/my-action
      #with:
      #username: ${{ inputs.username }}
      #token: ${{ secrets.token }}
#      - run: echo ${{env.firebase_credentials}}
#        shell: bash
      - name: lettura file
        run: echo $(cat credentials.txt)
        shell: bash
      - name: Verifica File
        run: echo 'reusable workflow!!!!'
        shell: bash
      - name: Operazioni Firebase DB
        uses: w9jds/firebase-action@master
        with:
          args: database:set --force --debug  --project databasericette-beeb7 /giuseppegargani/ecchime 'eccomi'
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_CREDENTIALS }}